### ISSUE TITLE
Date is off

### ISSUE THREAD

**Issue by rotero** [shooshx/BoardingBarcode#1]
it seems like the date encoded into the barcode is off by 2 days (at least when in central europe). when you enter the date +2 then all works like a charm

**Comment by shooshx** [comment]
Hey, do you mean the date field that says 9/9/2016 showing the wrong date or the day of the year number showing the wrong number?
What airport did you test it in?

**Comment by shooshx** [comment]
the day of year was wrong. fixed

**Comment by pbarov** [comment]
Hey,I used your app to enter in the Copenhagen airport but it didn’t work,i put a real flight number and false name,tried changing Aztec and pdf format but it failed ,what could be the reason for that?
