### ISSUE TITLE
Multi leg boarding pass

### ISSUE THREAD

**Issue by julianiaccopucci** [shooshx/BoardingBarcode#2]
The BCBP standard mentions multi leg boarding passes. I'm trying to cut the data for the second leg, but between the first and second legs, there are variable size fields.

Do you have any idea of how can I cut the data for the second leg, if there is a variable field size in the middle?

Thanks.

**Comment by shooshx** [comment]
Hey
I don't have any specific experience with such cases.
I guess the way I'd do it is to read the standard:

https://www.scribd.com/document/243611211/BCBP-Implementation-Guidev4-Jun2009-pdf

and figure out how to parse enough of the variable size fields to be able to skip them

**Comment by julianiaccopucci** [comment]
Thank you, this has been of loads of help.
