### ISSUE TITLE
Was this supposed to be built on windows only?

### ISSUE THREAD

**Issue by abhi-jha** [shooshx/BoardingBarcode#3]
I am trying to build it on CLion Linux with errors upon compilation : 

`/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/Scrt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
CMakeFiles/src.dir/build.make:276: recipe for target 'src' failed
make[2]: *** [src] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/src.dir/all' failed
make[1]: *** [CMakeFiles/src.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by shooshx** [comment]
The only way to build it is using emscripten. This file contains the command line:
https://github.com/shooshx/BoardingBarcode/blob/master/em_debug_build.bat
I've built it on windows but there's no reason it should not build on linux.
